# Generated by Django 4.0.2 on 2022-03-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Author'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
